import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/page";
import Footer from "@/components/footer/footer";

import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import CartContextProvider from "@/components/context/cartContext";
import MySessionProvider from "@/components/MySessionProvider/MySessionProvider";
import WishlistContextProvider from "@/components/context/wishListContext";

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className={`inter.className ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <MySessionProvider>
           <WishlistContextProvider>
          <CartContextProvider>
           <Navbar />
            <div className="container mx-auto pt-5">
              {children}
              <Toaster />
            </div>
            <Footer />
          </CartContextProvider>
           </WishlistContextProvider>
        </MySessionProvider>
      </body>
    </html>
  );
}
